<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Phim9x - <?= isset($head->title) ? $head->title : 'Trung tâm phim hoạt hình Việt Nam'; ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.4.0/css/all.css">
    <link rel="stylesheet" href="/assets/plugin/owlcarousel/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="/assets/plugin/owlcarousel/assets/owl.theme.default.css">
    <link href="/assets/css/styles.min.css?v=<?= time(); ?>" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/assets/css/intlTelInput.css">
</head>

<body>