 <div class="w-100 bg-primary fixed-top pt-3 pb-3">
     <div class="container d-flex justify-content-between align-items-center">
         <div class="fs-4 fw-500">
             <a href="/" class="text-decoration-none text-white">Phim9x</a>
         </div>
         <div class="layouts-search ms-2 me-3 ms-xl-0 me-xl-0 ms-lg-0 me-lg-0 d-flex align-items-center">
             <input autocomplete="off" placeholder="Tìm kiếm tên phim" class="fs-15 form-control text-white outline-0 bg-gray-dark box-shadow-none border-0" type="search" value="">
             <button class="btn border-0 btn-violet-dark box-shadow-none border-0">
                 <svg width="17" height="17" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 512 512">
                     <path d="M508.5 468.9L387.1 347.5c-2.3-2.3-5.3-3.5-8.5-3.5h-13.2c31.5-36.5 50.6-84 50.6-136C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c52 0 99.5-19.1 136-50.6v13.2c0 3.2 1.3 6.2 3.5 8.5l121.4 121.4c4.7 4.7 12.3 4.7 17 0l22.6-22.6c4.7-4.7 4.7-12.3 0-17zM208 368c-88.4 0-160-71.6-160-160S119.6 48 208 48s160 71.6 160 160-71.6 160-160 160z">
                     </path>
                 </svg>
             </button>
         </div>
         <div class="d-flex align-items-center">
             <?php if (!Auth::check()) : ?>
                 <div data-bs-toggle="modal" data-bs-target="#Login" role="button" class="border wh-2-3 d-flex align-items-center justify-content-center border-1 border-white rounded-circle">
                     <svg width="15" fill="white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                         <path d="M256 288c79.5 0 144-64.5 144-144S335.5 0 256 0 112 64.5 112 144s64.5 144 144 144zm128 32h-55.1c-22.2 10.2-46.9 16-72.9 16s-50.6-5.8-72.9-16H128C57.3 320 0 377.3 0 448v16c0 26.5 21.5 48 48 48h416c26.5 0 48-21.5 48-48v-16c0-70.7-57.3-128-128-128z">
                         </path>
                     </svg>
                 </div>
                 <div class="d-none align-items-center ms-3 text-white fs-14 fw-500 d-lg-flex">
                     <a role="button" data-bs-toggle="modal" data-bs-target="#Login" class="text-decoration-none">
                         <span class="text-white">Đăng nhập</span>
                     </a>
                     <span class="ms-2 me-2">/</span>
                     <a data-bs-toggle="modal" data-bs-target="#register" role="button" class="text-decoration-none">
                         <span class="text-white">Đăng ký</span>
                     </a>
                 </div>
             <?php else : ?>
                 <div role="button" class="border wh-2-3 d-flex align-items-center justify-content-center border-1 border-white rounded-circle">
                     <svg width="15" fill="white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                         <path d="M256 288c79.5 0 144-64.5 144-144S335.5 0 256 0 112 64.5 112 144s64.5 144 144 144zm128 32h-55.1c-22.2 10.2-46.9 16-72.9 16s-50.6-5.8-72.9-16H128C57.3 320 0 377.3 0 448v16c0 26.5 21.5 48 48 48h416c26.5 0 48-21.5 48-48v-16c0-70.7-57.3-128-128-128z">
                         </path>
                     </svg>
                 </div>
                 <div class="ms-2 text-white d-none d-lg-block" role="button"><?= Auth::user()->name; ?></div>
             <?php endif; ?>
         </div>
     </div>
 </div>
 <?php if (!Auth::check()) : ?>

     <!-- Modal -->
     <div class="modal fade" id="register" tabindex="-1" aria-labelledby="registerLabel" aria-hidden="true">
         <div class="modal-dialog">
             <div class="modal-content">
                 <div class="modal-header">
                     <div class="d-flex align-items-center">
                         <h1 class="modal-title fs-5 fw-500" id="registerLabel">Đăng ký</h1>
                         <a data-bs-toggle="modal" data-bs-target="#Login" type="button" class="text-decoration-none ms-2">
                             <h1 class="modal-title fs-5 fw-500 text-gray">Đăng nhập</h1>
                         </a>
                     </div>
                     <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                 </div>
                 <div class="modal-body">
                     <form action="/api/auth/register" method="POST" data-ajax>
                         <div class="mb-3">
                             <label for="name" class="form-label fs-14">Họ và tên</label>
                             <input type="text" class="form-control input_dark" name="name" id="name" aria-describedby="nameHelp">
                         </div>
                         <div class="mb-3">
                             <label for="phone" class="form-label fs-14">Số điện thoại</label>
                             <input type="tel" class="form-control input_dark" name="phone" id="phone" aria-describedby="phoneHelp">
                         </div>
                         <div class="mb-3">
                             <label for="username" class="form-label fs-14">Tên đăng nhập</label>
                             <input type="text" class="form-control input_dark" name="username" id="username" aria-describedby="usernameHelp">
                         </div>
                         <div class="mb-3">
                             <label for="password" class="form-label fs-14">Mật khẩu</label>
                             <input type="password" class="form-control input_dark" name="password" id="password">
                         </div>
                         <div class="mb-3">
                             <label for="confirm_password" class="form-label fs-14">Nhập lại mật khẩu</label>
                             <input type="password" class="form-control input_dark" name="confirm_password" id="confirm_password">
                         </div>
                         <button type="submit" class="btn btn-primary fs-14 mt-2 w-100" style="height: 3rem;">Tạo tài khoản</button>
                     </form>
                 </div>
             </div>
         </div>
     </div>
     <!-- Modal -->
     <div class="modal fade" id="Login" tabindex="-1" aria-labelledby="LoginLabel" aria-hidden="true">
         <div class="modal-dialog">
             <div class="modal-content">
                 <div class="modal-header">
                     <div class="d-flex align-items-center">
                         <h1 class="modal-title fs-5 fw-500" id="LoginLabel">Đăng nhập</h1>
                         <a data-bs-toggle="modal" data-bs-target="#register" type="button" class="text-decoration-none ms-2">
                             <h1 class="modal-title fs-5 fw-500 text-gray">Đăng ký</h1>
                         </a>
                     </div>
                     <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                 </div>
                 <div class="modal-body">
                     <form action="/api/auth/login" method="POST" data-ajax>
                         <div class="mb-3">
                             <label for="account" class="form-label fs-14">Tên đăng nhập</label>
                             <input type="account" class="form-control input_dark" name="account" id="account" aria-describedby="accountHelp">
                         </div>
                         <div class="mb-3">
                             <div class="d-flex align-items-center justify-content-between form-label">
                                 <label for="password" class=" fs-14">Mật khẩu</label>
                                 <a href="#" class="text-white fs-13 text-decoration-none">quên mật khẩu</a>
                             </div>
                             <input type="password" class="form-control input_dark" name="password" id="password">
                         </div>
                         <button type="submit" class="btn btn-primary fs-14 mt-2 w-100" style="height: 3rem;">Đăng nhập</button>
                     </form>
                 </div>
             </div>
         </div>
     </div>

 <?php endif; ?>