<?php
include_once __DIR__ . '/../layouts/head.phtml';
include_once __DIR__ . '/../layouts/sidebar.phtml';
?>
<div class="main">
    <div class="banner_film text-white" style="background-image: url('<?= $film->thumbnail; ?>');">
        <div class="container pb-4">
            <div class="d-flex flex-lg-row flex-column pt-3 align-items-start justify-content-between">
                <div>
                    <div class="fs-4 fw-500">Tên Phim: <?= $film->name; ?></div>
                    <div class="fs-6">
                        <?php if (isset($video->name)) : ?>
                            <span class="badge text-bg-danger"><?= $video->name; ?></span>
                        <?php else : ?>
                            <span class="badge text-bg-danger">Chưa phát sóng</span>
                        <?php endif; ?>
                        <span class="badge text-bg-main ms-2 fs-10 fs-lg-badge"><?= $film->category; ?></span>
                    </div>
                    <p class="fs-15 pb-0 text-white mt-1 contents_film"><?= $film->content; ?>
                    </p>
                </div>
                <div class="mt-2 mt-lg-0">
                    <p class="fs-15 pb-0 text-white mt-1">Tình trạng: hoàn tất</p>
                    <p class="fs-15 pb-0 text-white mt-1">Tập mới: <?= $film->note; ?></p>
                    <p class="fs-15 pb-0 text-white mt-1">Đăng tải <?= date('d/m/Y', $film->date); ?></p>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="mt-4">
            <div id="player" class="text-white text-center pt-3 pb-3 ps-3 pe-3">Xin lỗi tập phim này chưa cập nhập </div>
        </div>
        <div class="row gx-3 mt-3">
            <a class="col-auto text-white text-decoration-none" href="">Tải xuống </a>
            <a class="col-auto text-white text-decoration-none" data-episode>Tập tiếp theo </a>
            <a class=" col-auto text-white text-decoration-none" role="button" data-stop>Tạm dừng </a>
            <a class=" col-auto text-white text-decoration-none" href="">Tắt ADS </a>
        </div>
        <div class="row gx-3 mt-3">
            <?php foreach ($listPart as $Part) : ?>
                <?php $ckVideos = DB::connect()->find('video', ['IDFilm' => $film->IDFilm, 'IDPart' => $Part->IDPart], ['IDVideo ASC'])->get(); ?>
                <a class="col-auto" href="/<?= $film->slug; ?>/<?= $Part->IDPart; ?>/<?= (isset($ckVideos->episode)) ? $ckVideos->episode : 'null' ?>.html">
                    <span class=" badge text-bg-light <?= ($part->IDPart == $Part->IDPart) ? 'bg-main' : 'bg-primary'; ?> text-white fs-6 fw-500 "><?= $Part->name; ?></span>
                </a>
            <?php endforeach; ?>
        </div>
        <?php if (isset($video->name)) : ?>
            <div class="fs-6 fw-500 text-white mt-3 mb-2">Xem lướt</div>
            <div id=" slider" class="owl-carousel carousel_film text-white mt-1 position-relative">
                <?php foreach ($listEpisode as $Episode) : ?>
                    <div>
                        <a href="/<?= $film->slug; ?>/<?= $part->IDPart; ?>/<?= $Episode->episode; ?>.html" class="d-flex text-decoration-none">
                            <div class="d-flex flex-column position-relative"><img class="w-100 rounded-3" src="<?= $Episode->thumbnail; ?>" />
                                <div class="d-flex flex-column mt-1 chap_item">
                                    <p class="fs-14 text-white mb-0">
                                        <span class="badge text-bg-danger fs-10 fs-lg-badge"><?= $Episode->name; ?></span>
                                        <?php if ($Episode->episode == $video->episode) : ?>
                                            <span class="badge text-bg-main fs-10 fs-lg-badge">Đang phát</span>
                                        <?php endif; ?>
                                    </p>
                                </div>
                            </div>
                        </a>
                    </div><?php endforeach; ?>
            </div>
            <div class="fs-6 fw-500 text-white mt-3">Danh sách tập</div>
            <div class="row gx-3 mt-2">
                <?php foreach ($listEpisode as $Episode) : ?>
                    <div class="col-auto mb-3 item_episode <?= ($Episode->episode == $video->episode) ? 'active' : null; ?>">
                        <a href="/<?= $film->slug; ?>/<?= $part->IDPart; ?>/<?= $Episode->episode; ?>.html" class="d-flex text-decoration-none">
                            <span class="badge text-bg-light <?= ($Episode->episode == $video->episode) ? 'bg-main' : 'bg-primary'; ?> text-white fs-10 fs-6 fw-500">
                                <?= $Episode->name; ?>
                            </span>
                        </a>
                    </div>
                <?php   endforeach; ?>
            </div>
        <?php else : ?>
            <div class="fs-6 fw-500 text-white mt-3 mb-2">Xem lướt</div>
            <div class="text-gray mt-2">Chưa có tập phim nào</div>
            <div class="fs-6 fw-500 text-white mt-3`">Danh sách tập</div>
            <div class="text-gray mt-2">Chưa có tập phim nào</div>
        <?php endif; ?>
        <div class="mt-4">
            <div class="card card-body border-0">
                <?= $film->embed; ?>
            </div>
        </div>
    </div>
</div>
<?php include_once __DIR__ . '/../layouts/script.phtml'; ?>
<script src="/assets/plugin/owlcarousel/owl.carousel.min.js"></script>
<script src="https://ssl.p.jwpcdn.com/player/v/8.26.2/jwplayer.js" type="text/javascript"></script>
<script>
    jwplayer.key = "W7zSm81+mmIsg7F+fyHRKhF3ggLkTqtGMhvI92kbqf/ysE99";
</script>

<script type="text/javascript">
    $(document).ready(function() {

        $("a[data-stop]").click(function() {
            jwplayer().stop();
        });

        var next_episode = $(".item_episode.active ~ .item_episode a").attr('href');
        $("a[data-episode]").attr('href', next_episode);

        $(".owl-carousel").owlCarousel({

            startPosition: 0,
            items: 3,
            margin: 10,
            responsive: {

                // breakpoint from 768 up
                700: {
                    margin: 25,
                    items: 4,
                }
            }
        });
    });
    var playerInstance = jwplayer("player");

    playerInstance.setup({
        autostart: "viewable",
        advertising: {
            client: "vast",
            tag: "http://adserver.com/vastTag.xml"
        },
        image: "<?= isset($video->thumbnail) ? $video->thumbnail : $film->thumbnail; ?>",
        mute: false,
        allowfullscreen: true,
        playbackRateControls: true,
        preload: "auto",
        primary: "html5",
        responsive: true,
        width: "100%",
        aspectratio: "16:9",
        aboutlink: "https://zalo.me/0986379490",
        abouttext: "YODY DEV",
        cast: {},
        logo: {
            // file: "/assets/img/logo.png",
            link: "https://zalo.me/0986379490",
            hide: "true",
            position: "top-left"
        },
        captions: {
            color: "#fff",
            fontSize: 15,
            fontfamily: "Arial",
            edgeStyle: "raised"
        },
        skin: {
            name: "YODY DEV",
        }
        ,
        <?php if (isset($video->file)) : ?> playlist: "<?= $video->file; ?>"
        <?php endif; ?>

    }).on('time', function(e) {
        // $(this).currentTime(10);
    });
</script>
</div>
</div>
<?php
include_once __DIR__ . '/../layouts/end.phtml';
?>