<?php
include_once __DIR__ . '/../../layouts/head2.phtml';
?>
<link rel="stylesheet" href="/admin/extensions/sweetalert2/sweetalert2.min.css" />
<link rel="stylesheet" href="/admin/extensions/filepond/filepond.css" />
<link rel="stylesheet" href="/admin/extensions/filepond-plugin-image-preview/filepond-plugin-image-preview.css" />
<link rel="stylesheet" href="/admin/extensions/toastify-js/src/toastify.css" />
<link rel="stylesheet" href="/admin/extensions/choices.js/public/assets/styles/choices.css" />
<div id="app">
    <?php include_once __DIR__ . '/../../layouts/sidebar2.phtml'; ?>
    <div id="main">
        <header class="mb-3">
            <a href="#" class="burger-btn d-block d-xl-none">
                <i class="bi bi-justify fs-3"></i>
            </a>
        </header>

        <div class="page-heading">
            <div class="page-title">
                <div class="row">
                    <div class="col-12 col-md-6 order-md-1 order-last">
                        <h3>Danh sách tập phim </h3>
                        <p class="text-subtitle text-muted">
                            Nếu còn tập chưa có hãy thêm <a href="#" data-bs-toggle="modal" data-bs-target="#addFilm" onclick=" return false;">tại đây</a>
                        </p>
                    </div>
                    <div class="col-12 col-md-6 order-md-2 order-first">
                        <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a href="/admin/">Bảng điều khiển</a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">
                                    Danh sách tập phim
                                </li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>


            <!-- Minimal jQuery Datatable start -->
            <section class="section">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Danh sách tập</h5>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive datatable-minimal">
                            <table class="table" id="table2">
                                <thead>
                                    <tr>
                                        <th>Tên phim</th>
                                        <th>Tên phần</th>
                                        <th>Tập</th>
                                        <th>Thời gian</th>
                                        <th>hành động</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($list as $video) : ?>
                                        <tr>
                                            <td><?= DB::connect()->find('film', ['IDFilm' => $video->IDFilm])->get()->name; ?></td>
                                            <td><?= DB::connect()->find('part', ['IDFilm' => $video->IDFilm, 'IDPart' => $video->IDPart])->get()->name; ?></td>
                                            <td><?= $video->name; ?> (#<?= $video->episode; ?>)</td>
                                            <td><?= timeago($video->date); ?></td>
                                            <td class="d-flex align-items-center">
                                                <a href="/admin/film/<?= $video->IDFilm; ?>/part/<?= $video->IDPart; ?>/video/<?= $video->IDVideo; ?>/edit" class=" btn icon btn-primary">
                                                    <i class="bi bi-pencil"></i>
                                                    <span class="ms-1">Edit</span>
                                                </a>
                                                <form method="POST">
                                                    <input type="hidden" name="delete" value="<?= $video->IDVideo; ?>" />
                                                    <button type="submit" class="ms-2 btn icon btn-danger">
                                                        <i class="bi bi-x"></i>
                                                        <span class="ms-1">Delete</span>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </section>
        </div>

    </div>
</div>


<!--Basic Modal -->
<div class="modal fade text-left" id="addFilm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
        <form method="POST" class="modal-content" enctype="multipart/form-data">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel1">
                    Thêm Tập
                </h5>
                <button type="button" class="close rounded-pill" data-bs-dismiss="modal" aria-label="Close">
                    <i data-feather="x"></i>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="basicInput">Tên tập</label>
                    <input type="text" name="name" class="form-control" id="basicInput" placeholder="" />
                </div>
                <div class="form-group">
                    <label for="basicInput">Mã tập</label>
                    <input type="text" name="episode" class="form-control" id="basicInput" placeholder="" />
                </div>
                <div class="form-group">
                    <label for="basicInput">Url Video</label>
                    <input type="text" name="video" class="form-control" id="basicInput" placeholder="" />
                </div>
                <div class="form-group">
                    <label for="basicInput">Bìa phim</label>
                    <input type="file" name="thumbnail" class="basic-filepond" />
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn d-flex align-items-center" data-bs-dismiss="modal">
                    <span class="ms-2">Đóng</span>
                </button>
                <button type="submit" class="btn btn-primary ms-1 d-flex align-items-center" data-bs-dismiss="modal">
                    <span class="ms-2">Thêm</span>
                </button>
            </div>
        </form>
    </div>
</div>

<?php
include_once __DIR__ . '/../../layouts/script2.phtml';
?>

<script src="/admin/extensions/sweetalert2/sweetalert2.min.js"></script>
<script src="/admin/extensions/filepond-plugin-file-validate-size/filepond-plugin-file-validate-size.min.js"></script>
<script src="/admin/extensions/filepond-plugin-file-validate-type/filepond-plugin-file-validate-type.min.js"></script>
<script src="/admin/extensions/filepond-plugin-image-crop/filepond-plugin-image-crop.min.js"></script>
<script src="/admin/extensions/filepond-plugin-image-exif-orientation/filepond-plugin-image-exif-orientation.min.js"></script>
<script src="/admin/extensions/filepond-plugin-image-filter/filepond-plugin-image-filter.min.js"></script>
<script src="/admin/extensions/filepond-plugin-image-preview/filepond-plugin-image-preview.min.js"></script>
<script src="/admin/extensions/filepond-plugin-image-resize/filepond-plugin-image-resize.min.js"></script>
<script src="/admin/extensions/filepond/filepond.js"></script>
<script src="/admin/extensions/toastify-js/src/toastify.js"></script>
<script src="/admin/static/js/pages/filepond.js"></script>
<script src="/admin/extensions/choices.js/public/assets/scripts/choices.js"></script>
<script src="/admin/static/js/pages/form-element-select.js"></script>
<script src="/admin/extensions/jquery/jquery.min.js"></script>
<script src="/admin/extensions/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/admin/extensions/datatables.net-bs5/js/dataTables.bootstrap5.min.js"></script>
<script src="/admin/static/js/pages/datatables.js"></script>
<?php if (isset($data->status)) : ?>
    <script>
        const Swal2 = Swal.mixin({
            customClass: {
                input: 'form-control'
            }
        })
        Swal2.fire({
            icon: "<?= $data->status; ?>",
            text: '<?= $data->message; ?>'
        });
    </script>
<?php endif; ?>
<?php
include_once __DIR__ . '/../../layouts/end.phtml';
?>