<?php
include_once __DIR__ . '/../../layouts/head2.phtml';
?>
<link rel="stylesheet" href="/admin/extensions/sweetalert2/sweetalert2.min.css" />
<link rel="stylesheet" href="/admin/extensions/filepond/filepond.css" />
<link rel="stylesheet" href="/admin/extensions/filepond-plugin-image-preview/filepond-plugin-image-preview.css" />
<link rel="stylesheet" href="/admin/extensions/toastify-js/src/toastify.css" />
<link rel="stylesheet" href="/admin/extensions/choices.js/public/assets/styles/choices.css" />
<div id="app">
    <?php include_once __DIR__ . '/../../layouts/sidebar2.phtml'; ?>
    <div id="main">
        <header class="mb-3">
            <a href="#" class="burger-btn d-block d-xl-none">
                <i class="bi bi-justify fs-3"></i>
            </a>
        </header>

        <div class="page-heading">
            <div class="page-title">
                <div class="row">
                    <div class="col-12 col-md-6 order-md-1 order-last">
                        <h3>Chỉnh sửa phim</h3>
                        <p class="text-subtitle text-muted">
                            Lưu ý: hãy lưu lại sau khi sửa thông tin
                        </p>
                    </div>
                    <div class="col-12 col-md-6 order-md-2 order-first">
                        <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a href="/admin/">Bảng điều khiển</a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page">
                                    Chỉnh sửa phim
                                </li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>


            <!-- Minimal jQuery Datatable start -->
            <section class="section">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Chỉnh sửa phần</h5>
                    </div>
                    <form class="card-body" method="POST" >
                        <div class="form-group">
                            <label for="basicInput">Tên phần</label>
                            <input type="text" name="name" class="form-control" value="<?= $get->name ?>" id="basicInput" placeholder="" />
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn pt-2 pb-2 btn-primary w-100">
                                <span class="">Lưu thay đổi</span>
                            </button>
                        </div>
                    </form>
                </div>
            </section>
        </div>

    </div>
</div>




<?php
include_once __DIR__ . '/../../layouts/script2.phtml';
?>

<script src="/admin/extensions/sweetalert2/sweetalert2.min.js"></script>
<script src="/admin/extensions/filepond-plugin-file-validate-size/filepond-plugin-file-validate-size.min.js"></script>
<script src="/admin/extensions/filepond-plugin-file-validate-type/filepond-plugin-file-validate-type.min.js"></script>
<script src="/admin/extensions/filepond-plugin-image-crop/filepond-plugin-image-crop.min.js"></script>
<script src="/admin/extensions/filepond-plugin-image-exif-orientation/filepond-plugin-image-exif-orientation.min.js"></script>
<script src="/admin/extensions/filepond-plugin-image-filter/filepond-plugin-image-filter.min.js"></script>
<script src="/admin/extensions/filepond-plugin-image-preview/filepond-plugin-image-preview.min.js"></script>
<script src="/admin/extensions/filepond-plugin-image-resize/filepond-plugin-image-resize.min.js"></script>
<script src="/admin/extensions/filepond/filepond.js"></script>
<script src="/admin/extensions/toastify-js/src/toastify.js"></script>
<script src="/admin/static/js/pages/filepond.js"></script>
<script src="/admin/extensions/choices.js/public/assets/scripts/choices.js"></script>
<script src="/admin/static/js/pages/form-element-select.js"></script>
<script src="/admin/extensions/jquery/jquery.min.js"></script>
<script src="/admin/extensions/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/admin/extensions/datatables.net-bs5/js/dataTables.bootstrap5.min.js"></script>
<script src="/admin/static/js/pages/datatables.js"></script>
<?php if (isset($data->status)) : ?>
    <script>
        const Swal2 = Swal.mixin({
            customClass: {
                input: 'form-control'
            }
        })
        Swal2.fire({
            icon: "<?= $data->status; ?>",
            text: '<?= $data->message; ?>'
        });
    </script>
<?php endif; ?>
<?php
include_once __DIR__ . '/../../layouts/end.phtml';
?>